mode = "dark"
accent = "#A9C6B7"
selection = "#46594F"
selection_foreground = "#F0F5EE"
selection_background = "#46594F"
muted = "#B0C3B7"
background = "#26302D"
dark_background = "#1F2724"
darker_background = "#181F1D"
lighter_background = "#313D38"
foreground = "#DFE8E0"
dark_foreground = "#B0C3B7"
light_foreground = "#CDDED0"
bright_foreground = "#F0F5EE"
hyprland_active_border = "#8AA796"
hyprland_inactive_border = "#52665B"
red = "#DFE8E0"
green = "#A9C6B7"
yellow = "#CDDED0"
orange = "#CDDED0"
blue = "#A9C6B7"
magenta = "#DFE8E0"
cyan = "#B0C3B7"
brown = "#B0C3B7"
bright_red = "#F0F5EE"
bright_green = "#DFE8E0"
bright_yellow = "#F0F5EE"
bright_blue = "#CDDED0"
bright_magenta = "#DFE8E0"
bright_cyan = "#A9C6B7"
